-- Init table
CREATE TABLE IF NOT EXISTS "public"."experience" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "start" date NOT NULL,
    "end" date,
    "tags" json,
    "link" text
);

ALTER TABLE "public"."experience" OWNER TO "postgres";

ALTER TABLE "public"."experience" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."experience_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."experience"
    ADD CONSTRAINT "experience_pkey" PRIMARY KEY ("id");


ALTER TABLE "public"."experience" ENABLE ROW LEVEL SECURITY;

-- Add realtime
ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."experience";

-- Policies
CREATE POLICY "Enable all for authenticated users only"
ON "public"."experience"
AS permissive
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Enable read access for all users"
ON "public"."experience"
AS permissive
FOR SELECT
TO public
USING (true);